name: CI Pipeline for Microservice

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Authenticate with Docker Hub
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # ---- API Service ----
      - name: Build API Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./api-service
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/microservice-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/microservice-api:${{ github.sha }}

      # ---- Consumer Service ----
      - name: Build Consumer Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./consumer-service
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/microservice-consumer:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/microservice-consumer:${{ github.sha }}
